export const defaultColors = {
    primary: 'primary-500',
    secondary: 'secondary-500',
    success: 'success-500',
    info: 'info-500',
    warning: 'warning-500',
    error: 'error-500',
    text: 'neutral-800',
    'text-dimmed': 'neutral-400',
    'text-muted': 'neutral-600',
    'text-toned': 'neutral-700',
    'text-highlighted': 'neutral-900',
    'text-inverted': 'white',
    bg: 'white',
    'bg-muted': 'neutral-50',
    'bg-elevated': 'neutral-100',
    'bg-accented': 'neutral-200',
    'bg-inverted': 'neutral-800',
    border: 'neutral-200',
    'border-muted': 'neutral-300',
    'border-accented': 'primary-600',
    'border-inverted': 'neutral-800',
} satisfies Record<ThemeColor, ThemeShadeTintExtended>

export const defaultColorsDark = {
    primary: 'primary-400',
    secondary: 'secondary-400',
    success: 'success-400',
    info: 'info-400',
    warning: 'warning-400',
    error: 'error-400',
    text: 'neutral-100',
    'text-dimmed': 'neutral-500',
    'text-muted': 'neutral-400',
    'text-toned': 'neutral-300',
    'text-highlighted': 'neutral-50',
    'text-inverted': 'neutral-800',
    bg: 'neutral-900',
    'bg-muted': 'neutral-600',
    'bg-elevated': 'neutral-700',
    'bg-accented': 'neutral-800',
    'bg-inverted': 'white',
    border: 'neutral-800',
    'border-muted': 'neutral-700',
    'border-accented': 'primary-700',
    'border-inverted': 'white',
} satisfies Record<ThemeColor, ThemeShadeTintExtended>

export const defaultNuxtShades = {
    primary: '#00c950',
    secondary: '#2b7fff',
    success: '#00c950',
    info: '#2b7fff',
    warning: '#f0b100',
    error: '#fb2c36',
    neutral: '#737373'
}
